### ISSUE TITLE
Node_power_cycle produces error (dry_run = true)

### ISSUE THREAD

**Issue by kamfonik** [CCI-MOC/haas#404]
Calling "node_power_cycle" produces the following error message and traceback.
I have dry_run = true in haas.cfg

(.venv)kamfonik@dandini-ubuntu:~/Desktop/haas$ haas node_power_cycle 1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
DEBUG:moc.rest:Recieved api call node_power_cycle(u'1')
INFO:werkzeug:127.0.0.1 - - [24/Mar/2015 09:00:54] "POST /node/1/power_cycle HTTP/1.1" 500 -
DEBUG:requests.packages.urllib3.connectionpool:"POST /node/1/power_cycle HTTP/1.1" 500 291
Unexpected status code: 500
Response text:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/home/kamfonik/Desktop/haas/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/kamfonik/Desktop/haas/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/kamfonik/Desktop/haas/.venv/lib/python2.7/site-packages/werkzeug/local.py", line 224, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/kamfonik/Desktop/haas/moc/rest.py", line 201, in wsgi_handler
    response = request_handler(Request(environ))
  File "/home/kamfonik/Desktop/haas/moc/rest.py", line 182, in request_handler
    response_body = f(*positional_args)
  File "/home/kamfonik/Desktop/haas/haas/api.py", line 237, in node_power_cycle
    if not node.power_cycle():
  File "/home/kamfonik/Desktop/haas/haas/model.py", line 168, in power_cycle
    self._ipmitool(['chassis', 'bootdev', 'pxe'])
  File "/home/kamfonik/Desktop/haas/haas/model.py", line 157, in _ipmitool
    '-H', self.ipmi_host] + args)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by zenhack** [comment]
So from this it's pretty clear that the `dry_run` option isn't taking; it's calling `ipmitool` but that should be supressed. The question is why.

Try with `dry_run = True` (capitalized T)? I'm going to be very annoyed if that makes a difference, but...

The alternative is to put a break point at the end of `haas.config.load` and inspect the configuration:

    import pdb; pdb.set_trace()

I think we'd talked about meeting tonight, so if this is still an issue we can talk about it then.

**Comment by zenhack** [comment]
Err, nevermind. power_cycle needs `@no_dry_run` on top, apparently we missed that.

**Comment by zenhack** [comment]
@kamfonik, patches welcome, I'll get to it myself at some point.
