### ISSUE TITLE
[Bug] Can't detach the node from project

### ISSUE THREAD

**Issue by haydarkarrar** [CCI-MOC/haas#413]
It throws internal server error
I am trying this command
    $ haas project_detach_node <project_name> <node_name>

**Comment by zenhack** [comment]
Can you post the entire error?

Also, are you really just running `haas project_detach_node`? That command needs to be passed the name of the project and of the node; without those you should just get a message amount incorrect arguments.

**Comment by haydarkarrar** [comment]
Yeah I am passing the parameter!

**Comment by haydarkarrar** [comment]
This is full message:

lama@ubuntu:~/haas$ haas project_detach_node proj hp
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
DEBUG:requests.packages.urllib3.connectionpool:"POST /project/proj/detach_node HTTP/1.1" 500 291
Unexpected status code: 500
Response text:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by haydarkarrar** [comment]
This is error message I get in haas server running terminal:

ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.9.4-py2.7.egg/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.9.4-py2.7.egg/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.9.4-py2.7.egg/werkzeug/local.py", line 224, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/lama/haas/moc/rest.py", line 201, in wsgi_handler
    response = request_handler(Request(environ))
  File "/home/lama/haas/moc/rest.py", line 182, in request_handler
    response_body = f(*positional_args)
  File "/home/lama/haas/haas/api.py", line 189, in project_detach_node
    node.stop_console()
  File "/home/lama/haas/haas/dev_support.py", line 44, in wrapper
    return f(*args, **kwargs)
  File "/home/lama/haas/haas/model.py", line 209, in stop_console
    stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by zenhack** [comment]
Quoting Igibek Koishybayev (2015-04-09 11:26:06)
>    Yeah I am passing the parameter!

Okay. Can you post the full error message?

**Comment by zenhack** [comment]
I'm assuming you're just running this on a local machine (rather than a full setup with actual nodes available)? If so, you need to set `dry_run = True` in `haas.cfg`. If on the off chance you've got real nodes available, you need to install `ipmitool`.

**Comment by zenhack** [comment]
@haydarkarrar can you let us know if my suggestion fixed your problem?

**Comment by zenhack** [comment]
I am going to take the lack of response as meaning the problem is resolved. closing.
